server:
  port: 3270

spring:
  datasource:
    name: test
    url: jdbc:mysql://47.94.235.246:3306/JWT
    username: root
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.vita.jwt.jwt2.mapper

  configuration:
    map-underscore-to-camel-case: true